from datetime import datetime, timezone

from app.models.schemas import GenerateDocumentationRequest, GeneratedDocumentation, KTCaseRecord
from app.services.document_service import DocumentationComposer
from app.services.onedrive_service import OneDriveService


class DocumentationAgent:
    """Builds a structured KT document from submission and interview data."""

    def __init__(
        self,
        file_service: OneDriveService | None = None,
        composer: DocumentationComposer | None = None,
    ) -> None:
        self.file_service = file_service or OneDriveService()
        self.composer = composer or DocumentationComposer()

    def generate(
        self,
        case_record: KTCaseRecord,
        payload: GenerateDocumentationRequest,
    ) -> GeneratedDocumentation:
        submission = case_record.submission
        interview = case_record.interview
        summary = interview.summary if interview else "Knowledge transfer summary pending."
        risks = []
        if submission:
            risks.extend(submission.risks)
        if interview:
            risks.extend(interview.risks)
        checklist = [
            "Confirm all critical documents have been uploaded.",
            "Validate system access handover owners.",
            "Review pending deliverables and escalation paths.",
            "Share final KT document with manager and HR.",
        ]
        document = GeneratedDocumentation(
            title=f"KT Handover - {case_record.employee.employee_name}",
            summary=summary,
            key_responsibilities=interview.responsibilities if interview else [],
            daily_workflows=interview.workflows if interview else [],
            systems_and_tools=(interview.tools if interview else [])
            + (submission.systems if submission else []),
            project_insights=interview.project_insights if interview else [],
            risks_and_dependencies=risks,
            handover_checklist=checklist,
            reviewer_guidance=(
                f"Generated by {payload.generated_by}. Review for completeness, risks, "
                "and continuity coverage before approval."
            ),
            storage_path="",
            share_link=self.file_service.build_share_link(case_record.workflow.case_id),
            generated_at=datetime.now(timezone.utc),
        )
        draft_case = case_record.model_copy(update={"documentation": document})
        pdf_content = self.composer.build_pdf(draft_case)
        storage_path = self.file_service.save_binary_document(
            case_record.workflow.case_id,
            "knowledge_transfer.pdf",
            pdf_content,
        )
        return document.model_copy(update={"storage_path": storage_path})
